  version: '3.8'
  services:
    aegc-front:
      build: 
        context: ./frontend
        dockerfile: Dockerfile
      container_name: aegc-front-${APP_VERSION}
      image: aegc-front:${APP_VERSION}
      env_file:
        - ./.env
      ports:
        - "${PORT_FRONT}:80"
      restart: always
    
    aegc-back:
      build:
        context: ./backend
        dockerfile: Dockerfile
      container_name: aegc-back-${APP_VERSION}
      image: aegc-back:${APP_VERSION}
      env_file:
        - ./.env
      ports:
      - ${PORT_BACK}:3000
      restart: always

    nginx:
      image: nginx:latest
      container_name: nginx_proxy
      ports:
        - "80:80"   # HTTP public
        - "443:443" # HTTPS si tu veux SSL
      volumes:
        - /home/user00adm/nginx/conf.d:/etc/nginx/conf.d:ro
      depends_on:
        - aegc-front

